import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../../models/duplicate.dart';
import '../controllers/count_json_object_controller.dart';

class CountJsonObjectPage extends GetView<CountJsonObjectController> {
  Map<String, int> myMap = {};

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Count Json Object"),
        centerTitle: true,
        backgroundColor: Colors.grey[700],
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Form(
              child: _getTextField(),
            ),
            _getButton(),
          ],
        ),
      ),
    );
  }

  Widget _getTextField() {
    return Padding(
      padding: const EdgeInsets.only(left: 20, right: 20, top: 40),
      child: Center(
        child: TextFormField(
          controller: controller.jsonObjectController,
          decoration: InputDecoration(
              enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(10),
                  borderSide: BorderSide(color: Colors.grey)),
              focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(10),
                  borderSide: BorderSide(color: Colors.blue)),
              labelText: "Enter String"),
        ),
      ),
    );
  }

  Widget _getButton() {
    return Padding(
      padding: const EdgeInsets.only(top: 30),
      child: SizedBox(
        width: 100,
        height: 40,
        child: ElevatedButton(
          style: ElevatedButton.styleFrom(primary: Colors.grey[700]),
          onPressed: () {
            countJsonObject();
          },
          child: Center(
            child: Text("Click"),
          ),
        ),
      ),
    );
  }

  countJsonObject() {
    // var jsonObject = ;
    // var keyCount  = Autogenerated.keys(jsonObject).length;
    // var stores = json.decode('{ "name": "Pizza da Mario", "cuisine": "Italian", "reviews": [ { "score": 4.5, "review": "The pizza was amazing!" }, { "score": 5, "review": "Very friendly staff, excellent service!" } ] }');
    // (stores as Map<String, dynamic>).length;
    // print(stores);
    // List dummy =
    //     '{ "name": "Pizza da Mario", "cuisine": "Italian", "reviews": [ { "score": 4.5, "review": "The pizza was amazing!" }, { "score": 5.0, "review": "Very friendly staff, excellent service!" } ] }'
    //         .toLowerCase()
    //         .split('');
    // User user = User.fromJson(jsonDecode(dummy[0]));
    // for (var i = 0; i < dummy.length; i++) {
    //
    // }
    // print(user);


    // for(var i=0;i<s.length;i++){
    //   if(s[i]=="{"){
    //     count++;
    //   }
    // }
    //print("Total Object:- $count");
  }
}
// class Autogenerated {
//   String? name;
//   String? cuisine;
//   List<Reviews>? reviews;
//
//   Autogenerated({this.name, this.cuisine, this.reviews});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     name = json['name'];
//     cuisine = json['cuisine'];
//     if (json['reviews'] != null) {
//       reviews = <Reviews>[];
//       json['reviews'].forEach((v) {
//         reviews!.add(new Reviews.fromJson(v));
//       });
//     }
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['name'] = this.name;
//     data['cuisine'] = this.cuisine;
//     if (this.reviews != null) {
//       data['reviews'] = this.reviews!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }
//
// class Reviews {
//   double? score;
//   String? review;
//
//   Reviews({this.score, this.review});
//
//   Reviews.fromJson(Map<String, dynamic> json) {
//     score = json['score'];
//     review = json['review'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['score'] = this.score;
//     data['review'] = this.review;
//     return data;
//   }
// }
